### ISSUE TITLE
gminamoszczenica.eu

### ISSUE THREAD

**Issue by xxcriticxx** [hawkeye116477/PopupBlocker#2]
![capture](https://user-images.githubusercontent.com/15007183/29742512-9a240a98-8a4e-11e7-8351-c8151e55348c.PNG)

**Comment by hawkeye116477** [comment]
```
gminamoszczenica.eu###sbox-window
gminamoszczenica.eu###sbox-overlay
gminamoszczenica.eu##body.body-overlayed:style(overflow: visible!important;)
```
@xxcriticxx A te to postarali się, ale chyba aż za bardzo :smiley:. Moja reguła odblokowująca scroll nie do końca działa. Także proszę o pomoc @F4z.

**Comment by xxcriticxx** [comment]
@MajkiIT moze da rade @f4z busy teraz dorabia na adguardzie

**Comment by hawkeye116477** [comment]
@xxcriticxx @MajkiIT też coś chyba dziś czasu nie ma, a tak właściwie to od wczoraj od 20:53, pull request wciąż czeka :smile:.

**Comment by xxcriticxx** [comment]
weekend sie zaczol napewno piwo saczy

**Comment by hawkeye116477** [comment]
@xxcriticxx To coś długo to już trwa, co on Ferdek Kiepski :smiley:?

**Comment by MajkiIT** [comment]
Po dodaniu tych 2 reguł jest mam scrolla.
gminamoszczenica.eu###sbox-window
gminamoszczenica.eu###sbox-overlay

I nie piję piwa :P Już nadrabiam to co zamieściliście :P

**Comment by hawkeye116477** [comment]
@MajkiIT Wyczyść dane prywatne, scroll na chwilę się pojawi i zniknie. A 3 reguła działa, ale częsciowo, niby jest scroll, tyle, że tym środkowym przyciskiem myszy nie da rady scrollować.

**Comment by MajkiIT** [comment]
@hawkeye116477 
FF + clear cache + tryb prywatny i mam scrolla 2 z regułami.

**Comment by MajkiIT** [comment]
@hawkeye116477 
FF + clear cache + tryb prywatny i mam scrolla 2 z regułami.

**Comment by hawkeye116477** [comment]
@MajkiIT Tryb prywatny z ochroną przed śledzeniem czy raczej wyłączona? 
Ja sprawdziłem i scroll się chowa zarówno na Vivaldim, Chromium, jak i Waterfoksie.
Nie spamuj, bo bot się kręci i zbanuje jak @blocker999.

**Comment by hawkeye116477** [comment]
@MajkiIT Sprawdzałem jeszcze raz i scroll się chowa zarówno na Vivaldim, Chromium, jak i Waterfoksie. Możesz jeszcze raz sprawdzić tym razem na Chrome?
A u ciebie @xxcriticxx jak?

**Comment by MajkiIT** [comment]
@hawkeye116477 filtry mamy inne?

**Comment by hawkeye116477** [comment]
@MajkiIT Możliwe. Tyle tylko, że tam i tak mało blokuje. EasyPrivacy raczej tylko dodatkowo się załącza.
![screenshot_20170826_221052](https://user-images.githubusercontent.com/19818572/29744728-889a782c-8aab-11e7-8394-ea6ff70894ba.png)
![screenshot_20170826_221107](https://user-images.githubusercontent.com/19818572/29744729-8a2b0594-8aab-11e7-96fd-485dd4e9080e.png)
![Uploading Screenshot_20170826_221120.png…]()

**Comment by MajkiIT** [comment]
Ja nie mam Fanboy ....

**Comment by hawkeye116477** [comment]
@MajkiIT Easyprivacy, Fanboys Social i nasza lista ciastek coś tam tylko blokuje, ale wyłączyłem to i nic, dalej jest to samo.

**Comment by xxcriticxx** [comment]
z @MajkiIT regulami pokazuje mi scroll arrow z prawej i potem znika

**Comment by hawkeye116477** [comment]
@xxcriticxx A no właśnie, czyli @MajkiIT coś mnie wkręca albo sobie wyobraża, że ten scroll tam jest cały czas :smiley:.

Z tymi trzema niby jest pasek od scrolla cały czas, ale środkowym przyciskiem myszy nie można scrollować, no bo właśnie, to pewnie coś ma związek z tymi błędami, że czegoś tu brakuje, coś jest niezdefiniowane.
```
gminamoszczenica.eu###sbox-window
gminamoszczenica.eu###sbox-overlay
gminamoszczenica.eu##body.body-overlayed:style(overflow: visible!important;)
```

**Comment by xxcriticxx** [comment]
na chromie jest tak samo scroll dziala z @hawkeye116477 regulami z @MajkiIT znika

**Comment by hawkeye116477** [comment]
@xxcriticxx Jak to działa, możesz środkowym przyciskiem myszy scrollować? Bo u mnie coś nie chce, można tylko przesuwać najeżdżając.

**Comment by F4z** [comment]
Moglibyście sprawdzić, czy po dodaniu tych reguł wszystko działa jak powinno?
`gminamoszczenica.eu###sbox-window`
`gminamoszczenica.eu###sbox-overlay`
`gminamoszczenica.eu##body.body-overlayed:style(overflow: visible!important;)`
`gminamoszczenica.eu##script:inject(addEventListener-defuser.js, mousewheel)`

**Comment by hawkeye116477** [comment]
@F4z Jesteś wielki, działa jak natura chciała :smile:.

**Comment by MajkiIT** [comment]
@hawkeye116477 dla jasności nie bajerowałem, bo po jakiego grzyba miałbym to robić?

https://www.screencast.com/t/Ra2SJSDP8m

**Comment by hawkeye116477** [comment]
@MajkiIT A bo ja wiem, może zdawało ci się, że dziś 1 kwietnia i Prima Aprilis chciałeś zrobić :smiley:.
Relikt przeszłości flash jest wymagany... Ale z tego co widzę, to ty robisz wszystko na zwykłym trybie , a nie prywatnym i masz już stronę otwartą, a potem robisz refresh, no to nic dziwnego, że to działa poprawnie. Scroll się blokował tylko za 1 wejściem na stronę. No chyba, że wcześniej czyściłeś dane. Jednakże widać, że uBlock blokuje tylko 1 element, a zdaje się, że powinien więcej, a może po prostu ten popup pojawia się tylko czasami.
Teraz sprawdziłem i uBlock nie blokuje popupu, bo teraz jakoś właśnie się nie pojawia.
A zaraz chwila, impreza była wczoraj, więc już tego dlatego zapewne nie ma.
