### ISSUE TITLE
swinoujskie.info

### ISSUE THREAD

**Issue by xxcriticxx** [hawkeye116477/PopupBlocker#4]
![capture](https://user-images.githubusercontent.com/15007183/29743423-c7309be4-8a5f-11e7-85e8-48fd73523d31.PNG)

**Comment by hawkeye116477** [comment]
@xxcriticxx Nie postarali się: `swinoujskie.info###snppopup-welcome` :smile:.

**Comment by hawkeye116477** [comment]
Test

**Comment by hawkeye116477** [comment]
test

**Comment by hawkeye116477** [comment]
Test
